### ISSUE TITLE
Unity is proprietary, user subjugating software

### ISSUE THREAD

**Issue by mattl** [ajman1101/Remy-The-Flossopher#5]
Please consider a switch to a free software game library.

**Comment by ajman1101** [comment]
Not really sure how we are subjugating Unity's proprietary software. Email me with your understanding of the situation. I am only a student and not a lawyer and I am not well versed in these legal issues.

As for using a free software game library, this game is a demo of another project of mine, [Twine2Unity](https://github.com/ajman1101/Twine2Unity), a parser for twine files into a usable format for unity. As the game is released in LGPLv3, you are free to use the game script I wrote and the game as a base to remake/remix it into another game library, just be sure to have proper attribution back to this project. 

Thanks for checking out the project!

**Comment by mattl** [comment]
You're not subjugating Unity, you're subjugating users by asking them to Unity to hack on your game. Doesn't seem good for a free sw game to have a proprietary library.

I hope you'll make a game about Remy that is free software from the ground up.

**Comment by ajman1101** [comment]
Well the script and other assets are  LGPL, so anyone is free to port to a different free software library.
